"""rename user.config to user.integrations field

Revision ID: ac0dcc80654f
Revises: cc2699cdccaf
Create Date: 2025-06-11 21:35:32.814635

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac0dcc80654f"
down_revision: Union[str, None] = "cc2699cdccaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_apscheduler_jobs_next_run_time"), table_name="apscheduler_jobs"
    )
    op.drop_table("apscheduler_jobs")
    op.add_column(
        "users",
        sa.Column(
            "integrations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("users", "config")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "integrations")
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", sa.VARCHAR(length=191), autoincrement=False, nullable=False),
        sa.Column(
            "next_run_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("job_state", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("apscheduler_jobs_pkey")),
    )
    op.create_index(
        op.f("ix_apscheduler_jobs_next_run_time"),
        "apscheduler_jobs",
        ["next_run_time"],
        unique=False,
    )
    # ### end Alembic commands ###
